### ISSUE TITLE
Error: unknown command "doctl" for "doctl"

### ISSUE THREAD

**Issue by laukstein** [do-community/example-doctl-action#9]
https://github.com/marketplace/actions/github-action-for-digitalocean-doctl#usage has invalid details  on recommending

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save testing-cluster

When it is used Github Actions fails with error "unknown command "doctl" for "doctl"

![grabilla g10584](https://user-images.githubusercontent.com/183966/80489775-006df900-8969-11ea-966f-2ed1de44ed1f.png)

It shouldn't contain `doctl`, should be 

    - name: Save DigitalOcean kubeconfig
      run: kubernetes cluster kubeconfig save testing-cluster

**Comment by andrewsomething** [comment]
Hi @laukstein,

As shown in the first step, the example is using `digitalocean/action-doctl@v2`:

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

`@v2` has a different interface than `@master` which maintains the old behavior in order to not break existing users.  

See the release notes here: https://github.com/digitalocean/action-doctl/releases/tag/v2.0.0 and the RFC for more details on the changes: https://github.com/digitalocean/action-doctl/issues/27
